/*
 * This C++ source file was generated by the Gradle 'init' task.
 */
#ifndef APP_H
#define APP_H

#include <string>

namespace emel_lang {
    class Greeter {
        public:
        std::string greeting();
    };
}

#endif
