/*
 * This C++ source file was generated by the Gradle 'init' task.
 */

#include <iostream>
#include <stdlib.h>
#include <string>
#include "../headers/app.h"

int main(int argc, char **argv) {
    std::cout << "Hello, world!" << std::endl;
    return 0;   
}
